name: PR Builder
permissions:
  contents: read
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    name: Swift ${{ matrix.swift }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        swift: [ "6.2" ]
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Swift ${{ matrix.swift }}
        uses: swift-actions/setup-swift@364295d9c23900ce04d4e5cc708387921b4e50f9 # v3
        with:
          swift-version: ${{ matrix.swift }}
          skip-verify-signature: true
      - name: Swift build
        run: swift build
      - name: Swift test
        run: swift test
