name: Doc Builder
permissions:
  contents: read
on:
  release:
    types: [published]
jobs:
  build:
    name: Doc Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Swift 6.2
        uses: swift-actions/setup-swift@364295d9c23900ce04d4e5cc708387921b4e50f9 # v3
        with:
          swift-version: 6.2
          skip-verify-signature: true
      - name: Swift build
        run: swift build
      - name: Build docs
        run: swift package --allow-writing-to-directory docs generate-documentation --target AppStoreServerLibrary --product AppStoreServerLibrary --disable-indexing --hosting-base-path app-store-server-library-swift --output-path docs
      - name: Upload docs
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: docs
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy docs
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
